import { resolve } from 'node:path';

export function createLandingAssetCopyPlan({ repoRoot, siteRoot } = {}) {
  if (!repoRoot) {
    throw new Error('repoRoot is required to create the landing asset copy plan');
  }
  if (!siteRoot) {
    throw new Error('siteRoot is required to create the landing asset copy plan');
  }

  const legacyStatic = resolve(siteRoot, 'legacy/go-renderer/internal/site/static');
  const legacyInstallers = resolve(siteRoot, 'legacy/go-renderer/internal/site/installers');

  return {
    copies: [
      copy('install.sh', resolve(repoRoot, 'install.sh'), resolve(siteRoot, 'public/install.sh')),
      copy('install.ps1', resolve(repoRoot, 'scripts/install.ps1'), resolve(siteRoot, 'public/install.ps1')),
      copy('install.cmd', resolve(repoRoot, 'scripts/install.cmd'), resolve(siteRoot, 'public/install.cmd')),
      copy(
        'legacy install.ps1',
        resolve(repoRoot, 'scripts/install.ps1'),
        resolve(legacyInstallers, 'install.ps1'),
      ),
      copy(
        'legacy install.cmd',
        resolve(repoRoot, 'scripts/install.cmd'),
        resolve(legacyInstallers, 'install.cmd'),
      ),
      copy('benchmarks.json', resolve(repoRoot, 'benchmarks.json'), resolve(siteRoot, 'src/data/benchmarks.json')),
      // webpages/landing/src/data/progress.json removed 2026-05-16
      // (backlog-efficiency #1): nothing in the Astro site imports it — it was a
      // dead 5.2 MB verbatim mirror of the canonical backlog. The landing
      // roadmap is rendered from the slim go:embed mirror in the legacy
      // go-renderer, regenerated by `go run ./cmd/progress write`.
      copy('favicon.ico', resolve(legacyStatic, 'favicon.ico'), resolve(siteRoot, 'public/static/favicon.ico')),
      copy(
        'favicon-16x16.png',
        resolve(legacyStatic, 'favicon-16x16.png'),
        resolve(siteRoot, 'public/static/favicon-16x16.png'),
      ),
      copy(
        'favicon-32x32.png',
        resolve(legacyStatic, 'favicon-32x32.png'),
        resolve(siteRoot, 'public/static/favicon-32x32.png'),
      ),
      copy(
        'apple-touch-icon.png',
        resolve(legacyStatic, 'apple-touch-icon.png'),
        resolve(siteRoot, 'public/static/apple-touch-icon.png'),
      ),
      copy(
        'android-chrome-192x192.png',
        resolve(legacyStatic, 'android-chrome-192x192.png'),
        resolve(siteRoot, 'public/static/android-chrome-192x192.png'),
      ),
      copy(
        'android-chrome-512x512.png',
        resolve(legacyStatic, 'android-chrome-512x512.png'),
        resolve(siteRoot, 'public/static/android-chrome-512x512.png'),
      ),
      copy('social-card.png', resolve(legacyStatic, 'social-card.png'), resolve(siteRoot, 'public/static/social-card.png')),
      copy(
        'go-gopher-bear-lowpoly.png',
        resolve(legacyStatic, 'go-gopher-bear-lowpoly.png'),
        resolve(siteRoot, 'public/static/go-gopher-bear-lowpoly.png'),
      ),
      copy(
        'gormes-agent-logo-blue.svg',
        resolve(repoRoot, 'assets/gormes-agent-logo-blue.svg'),
        resolve(siteRoot, 'public/static/gormes-agent-logo-blue.svg'),
      ),
    ],
  };
}

export function parseReleaseData(raw, { source = 'cmd/gormes/version.go', errorSource = source } = {}) {
  const match = raw.match(/var\s+Version\s*=\s*"([^"]+)"/);
  if (!match) {
    throw new Error(`could not read Version from ${errorSource}`);
  }
  const aliasMatch = raw.match(/var\s+VersionDateAlias\s*=\s*"([^"]+)"/);
  if (!aliasMatch) {
    throw new Error(`could not read VersionDateAlias from ${errorSource}`);
  }

  const version = match[1];
  const dateAlias = aliasMatch[1];
  return {
    version,
    tag: `v${version}`,
    date_alias: dateAlias,
    url: `https://github.com/TrebuchetDynamics/gormes-agent/releases/tag/v${version}`,
    source,
  };
}

function copy(label, source, target) {
  return { label, source, target };
}
