package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

const termuxBootDir = ".termux/boot"
const termuxBootScriptName = "gormes-gateway.sh"

var termuxBootScriptTemplate = `#!/data/data/com.termux/files/usr/bin/sh
# Auto-generated by gormes gateway boot-install
# Starts the Gormes gateway inside tmux on Termux boot.
termux-wake-lock
exec tmux new-session -d -s gormes-gateway "gormes gateway"
`

func newGatewayBootInstallCommand() *cobra.Command {
	return &cobra.Command{
		Use:          "boot-install",
		Short:        "Install Termux:Boot script for gateway auto-start",
		SilenceUsage: true,
		RunE:         runGatewayBootInstall,
	}
}

func newGatewayBootUninstallCommand() *cobra.Command {
	return &cobra.Command{
		Use:          "boot-uninstall",
		Short:        "Remove Termux:Boot script for gateway auto-start",
		SilenceUsage: true,
		RunE:         runGatewayBootUninstall,
	}
}

func runGatewayBootInstall(cmd *cobra.Command, _ []string) error {
	if !gatewayTermuxDetected() {
		return fmt.Errorf("gateway boot-install is only available on Termux")
	}
	home := os.Getenv("HOME")
	if home == "" {
		return fmt.Errorf("HOME not set")
	}
	bootDir := filepath.Join(home, termuxBootDir)
	if err := os.MkdirAll(bootDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", bootDir, err)
	}
	scriptPath := filepath.Join(bootDir, termuxBootScriptName)
	if err := os.WriteFile(scriptPath, []byte(termuxBootScriptTemplate), 0o755); err != nil {
		return fmt.Errorf("write %s: %w", scriptPath, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "gateway boot-install: wrote %s\n", scriptPath)
	fmt.Fprintln(cmd.OutOrStdout(), "gateway boot-install: install the Termux:Boot app and reboot to auto-start")
	return nil
}

func runGatewayBootUninstall(cmd *cobra.Command, _ []string) error {
	if !gatewayTermuxDetected() {
		return fmt.Errorf("gateway boot-uninstall is only available on Termux")
	}
	home := os.Getenv("HOME")
	if home == "" {
		return fmt.Errorf("HOME not set")
	}
	scriptPath := filepath.Join(home, termuxBootDir, termuxBootScriptName)
	if err := os.Remove(scriptPath); err != nil {
		if os.IsNotExist(err) {
			fmt.Fprintf(cmd.OutOrStdout(), "gateway boot-uninstall: %s does not exist\n", scriptPath)
			return nil
		}
		return fmt.Errorf("remove %s: %w", scriptPath, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "gateway boot-uninstall: removed %s\n", scriptPath)
	return nil
}
