// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/TrebuchetDynamics/gormes-agent/internal/adapters/apiserver/ui/shell"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"status-grid\" id=\"status-bar\" hx-get=\"/dashboard/status\" hx-trigger=\"load, every 5s\" hx-swap=\"innerHTML\"><div class=\"status-box\"><div class=\"val\">—</div><div class=\"lbl\">Phase</div></div><div class=\"status-box\"><div class=\"val\">—</div><div class=\"lbl\">Model</div></div><div class=\"status-box\"><div class=\"val\">—</div><div class=\"lbl\">Session</div></div></div><div class=\"row\"><div class=\"col\"><div class=\"card\"><h2>🧠 Brain Feed</h2><div class=\"terminal-box\" id=\"brain-feed\" hx-ext=\"sse\" sse-connect=\"/dashboard/events\" sse-swap=\"frame\" hx-swap=\"beforeend\" style=\"max-height:500px\"><div class=\"line thinking\">Waiting for agent activity…</div></div></div><div class=\"card\"><h2>📋 Recent Sessions</h2><div id=\"session-list\" hx-get=\"/dashboard/sessions-fragment\" hx-trigger=\"load, every 30s\" hx-swap=\"innerHTML\"><div style=\"color:var(--dim)\">Loading sessions…</div></div></div></div><div class=\"col\"><div class=\"card\"><h2>🎯 Task Injection</h2><form hx-post=\"/agent/execute\" hx-target=\"#task-result\" hx-swap=\"innerHTML\"><input type=\"text\" name=\"prompt\" placeholder=\"Inject new directive…\" required> <button type=\"submit\"><span class=\"htmx-indicator spin\">⏳</span> <span>Execute</span></button></form><div id=\"task-result\"></div></div><div class=\"card\"><h2>🧩 Memory Nodes</h2><div id=\"memory-list\" hx-get=\"/dashboard/memory\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><div style=\"color:var(--dim)\">Loading memory…</div></div><div id=\"memory-details\" style=\"margin-top:8px\"></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = shell.Layout("Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
