package llm

import (
	"context"
	"encoding/json"
	"io"
)

const defaultCodexResponsesPath = "/v1/responses"

// ProviderTransport is the Go-native equivalent of Hermes' transport layer:
// it owns provider request shape and provider stream fixture normalization,
// but not HTTP client construction, credential refresh, retries, or kernel
// orchestration.
type ProviderTransport interface {
	APIMode() string
	BuildRequest(ChatRequest) (ProviderRequest, error)
	OpenFixtureStream(io.ReadCloser, ProviderRequest) (Stream, error)
}

// ProviderRequest captures the provider-native request generated by a
// transport. ToolDescriptors are the sanitized descriptors required when a
// stream decoder repairs or validates tool-call arguments.
type ProviderRequest struct {
	APIMode         string
	Path            string
	Body            []byte
	ToolDescriptors []ToolDescriptor
}

type chatCompletionsTransport struct{}
type anthropicMessagesTransport struct{}
type bedrockConverseTransport struct{}
type codexResponsesTransport struct{}

var providerTransports = map[string]ProviderTransport{
	"chat_completions":   chatCompletionsTransport{},
	"anthropic_messages": anthropicMessagesTransport{},
	"bedrock_converse":   bedrockConverseTransport{},
	"codex_responses":    codexResponsesTransport{},
}

func GetProviderTransport(apiMode string) (ProviderTransport, bool) {
	transport, ok := providerTransports[apiMode]
	return transport, ok
}

func (chatCompletionsTransport) APIMode() string { return "chat_completions" }

func (chatCompletionsTransport) BuildRequest(req ChatRequest) (ProviderRequest, error) {
	body, descriptors, err := (&httpClient{}).buildOpenAICompatibleChatRequestBody(req)
	if err != nil {
		return ProviderRequest{}, err
	}
	return ProviderRequest{
		APIMode:         "chat_completions",
		Path:            defaultChatCompletionsPath,
		Body:            body,
		ToolDescriptors: descriptors,
	}, nil
}

func (chatCompletionsTransport) OpenFixtureStream(body io.ReadCloser, req ProviderRequest) (Stream, error) {
	return newChatStream(body, "", req.ToolDescriptors), nil
}

func (anthropicMessagesTransport) APIMode() string { return "anthropic_messages" }

func (anthropicMessagesTransport) BuildRequest(req ChatRequest) (ProviderRequest, error) {
	descriptors := SanitizeToolDescriptors(req.Tools)
	req.Tools = descriptors
	payload, err := buildAnthropicRequest(req)
	if err != nil {
		return ProviderRequest{}, err
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return ProviderRequest{}, err
	}
	return ProviderRequest{
		APIMode:         "anthropic_messages",
		Path:            defaultAnthropicMessagesPath,
		Body:            body,
		ToolDescriptors: descriptors,
	}, nil
}

func (anthropicMessagesTransport) OpenFixtureStream(body io.ReadCloser, req ProviderRequest) (Stream, error) {
	return newAnthropicStream(body, req.ToolDescriptors), nil
}

func (bedrockConverseTransport) APIMode() string { return "bedrock_converse" }

func (bedrockConverseTransport) BuildRequest(req ChatRequest) (ProviderRequest, error) {
	payload, err := buildBedrockConversePayload(req)
	if err != nil {
		return ProviderRequest{}, err
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return ProviderRequest{}, err
	}
	return ProviderRequest{
		APIMode:         "bedrock_converse",
		Path:            "bedrock:ConverseStream",
		Body:            body,
		ToolDescriptors: SanitizeToolDescriptors(req.Tools),
	}, nil
}

func (bedrockConverseTransport) OpenFixtureStream(body io.ReadCloser, _ ProviderRequest) (Stream, error) {
	defer body.Close()
	raw, err := io.ReadAll(body)
	if err != nil {
		return nil, err
	}
	var frames []map[string]any
	if err := json.Unmarshal(raw, &frames); err != nil {
		return nil, err
	}
	events, err := decodeBedrockStreamEvents(frames, nil)
	if err != nil {
		return nil, err
	}
	return newStaticProviderStream(events), nil
}

func (codexResponsesTransport) APIMode() string { return "codex_responses" }

func (codexResponsesTransport) BuildRequest(req ChatRequest) (ProviderRequest, error) {
	payload, err := buildCodexResponsesPayload(req)
	if err != nil {
		return ProviderRequest{}, err
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return ProviderRequest{}, err
	}
	return ProviderRequest{
		APIMode:         "codex_responses",
		Path:            defaultCodexResponsesPath,
		Body:            body,
		ToolDescriptors: SanitizeToolDescriptors(req.Tools),
	}, nil
}

func (codexResponsesTransport) OpenFixtureStream(body io.ReadCloser, req ProviderRequest) (Stream, error) {
	defer body.Close()
	raw, err := io.ReadAll(body)
	if err != nil {
		return nil, err
	}
	var response codexResponsesResponse
	if err := json.Unmarshal(raw, &response); err != nil {
		return nil, err
	}
	normalized, err := normalizeCodexResponsesResponseWithTools(response, req.ToolDescriptors)
	if err != nil {
		return nil, err
	}
	return newStaticProviderStream(normalized.Events), nil
}

type staticProviderStream struct {
	events []Event
	index  int
	closed bool
}

func newStaticProviderStream(events []Event) *staticProviderStream {
	return &staticProviderStream{events: events}
}

func (s *staticProviderStream) SessionID() string { return "" }

func (s *staticProviderStream) Recv(ctx context.Context) (Event, error) {
	select {
	case <-ctx.Done():
		return Event{}, ctx.Err()
	default:
	}
	if s.closed || s.index >= len(s.events) {
		return Event{}, io.EOF
	}
	event := s.events[s.index]
	s.index++
	return event, nil
}

func (s *staticProviderStream) Close() error {
	s.closed = true
	return nil
}
