package inventory

// PlatformImplementationStatus classifies how much of one upstream Hermes
// gateway platform has a native Gormes surface today.
type PlatformImplementationStatus string

const (
	PlatformStatusImplemented PlatformImplementationStatus = "implemented"
	PlatformStatusPartial     PlatformImplementationStatus = "partial"
	PlatformStatusRowBacked   PlatformImplementationStatus = "row_backed"
	PlatformStatusExcluded    PlatformImplementationStatus = "excluded"
	PlatformStatusOwned       PlatformImplementationStatus = "owned"
)

// PlatformSurfaceStatus records whether one observable platform capability is
// already implemented, partially implemented, row-backed, intentionally not
// applicable, or owned by a Go-native Gormes surface.
type PlatformSurfaceStatus string

const (
	PlatformSurfaceImplemented   PlatformSurfaceStatus = "implemented"
	PlatformSurfacePartial       PlatformSurfaceStatus = "partial"
	PlatformSurfaceRowBacked     PlatformSurfaceStatus = "row_backed"
	PlatformSurfaceNotApplicable PlatformSurfaceStatus = "not_applicable"
	PlatformSurfaceOwned         PlatformSurfaceStatus = "owned"
)

// PlatformKind distinguishes real operator channels from local/runtime-only
// gateway surfaces that Hermes still exposes through the same Platform enum.
type PlatformKind string

const (
	PlatformKindChannel PlatformKind = "channel"
	PlatformKindRuntime PlatformKind = "runtime"
	PlatformKindWebhook PlatformKind = "webhook"
	PlatformKindLocal   PlatformKind = "local"
)

// PlatformManifestEntry is the source-backed platform inventory used by
// gateway/channel planning. It is deliberately data-only: tests compare it to
// upstream Hermes source without starting live SDKs, sockets, webhooks, QR
// flows, or credential readers.
type PlatformManifestEntry struct {
	ID                      string
	DisplayName             string
	Kind                    PlatformKind
	Status                  PlatformImplementationStatus
	HermesSource            string
	GormesSurface           string
	RequiresLiveCredentials bool
	Inbound                 PlatformSurfaceStatus
	Outbound                PlatformSurfaceStatus
	Media                   PlatformSurfaceStatus
	Commands                PlatformSurfaceStatus
	Toolset                 PlatformSurfaceStatus
	Config                  PlatformSurfaceStatus
	Pairing                 PlatformSurfaceStatus
	Delivery                PlatformSurfaceStatus
	BacklogOwner            string
	Notes                   string
}

// HermesGatewayPlatformManifest returns a copy of the current Hermes gateway
// Platform enum and connector inventory as understood by Gormes. Unsupported
// platforms remain explicit row-backed entries instead of disappearing from
// status, docs, or follow-up planning.
func HermesGatewayPlatformManifest() []PlatformManifestEntry {
	manifest := []PlatformManifestEntry{
		{ID: "local", DisplayName: "Local runtime", Kind: PlatformKindLocal, Status: PlatformStatusOwned, HermesSource: "gateway/config.py:Platform.LOCAL", GormesSurface: "cmd/gormes root/TUI/oneshot", Inbound: PlatformSurfaceOwned, Outbound: PlatformSurfaceOwned, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfacePartial, Toolset: PlatformSurfacePartial, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceOwned, BacklogOwner: "Phase 4.I / Phase 5.Q", Notes: "Local is a runtime surface, not an external channel."},
		{ID: "telegram", DisplayName: "Telegram", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/telegram/adapter.py", GormesSurface: "internal/channels/telegram + cmd/gormes gateway", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfacePartial, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B / Phase 2.F", Notes: "Primary dogfood channel; Hermes moved Telegram to a bundled platform plugin; live tokens are never needed for manifest tests."},
		{ID: "discord", DisplayName: "Discord", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/discord/adapter.py", GormesSurface: "internal/channels/discord", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B / Phase 2.F", Notes: "Hermes now exposes Discord as a bundled platform plugin; Gormes has native mention-aware ingress and reply delivery, while richer plugin adapter parity remains partial."},
		{ID: "whatsapp", DisplayName: "WhatsApp", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/whatsapp/adapter.py", GormesSurface: "internal/channels/whatsapp", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B.4", Notes: "Hermes moved WhatsApp to a bundled platform plugin; native transport startup and QR UX are outside the closed first-pass contract."},
		{ID: "slack", DisplayName: "Slack", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/slack/adapter.py", GormesSurface: "internal/channels/slack", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B.3 / Phase 5.O", Notes: "Hermes moved Slack to a bundled platform plugin; Socket Mode and command registry wiring are native; runtime management CLI remains row-backed."},
		{ID: "signal", DisplayName: "Signal", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "gateway/platforms/signal.py", GormesSurface: "internal/channels/signal", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.A", Notes: "Shared-chassis behavior is present; bootstrap/transport remains paused."},
		{ID: "mattermost", DisplayName: "Mattermost", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/mattermost/adapter.py", GormesSurface: "internal/channels/threadtext", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.C", Notes: "Hermes now exposes Mattermost as a bundled platform plugin; thread-text base contracts exist and the adapter remains row-backed."},
		{ID: "matrix", DisplayName: "Matrix", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/matrix/adapter.py", GormesSurface: "internal/channels/threadtext", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.C", Notes: "Hermes moved Matrix to a bundled platform plugin; thread-text base contracts exist and the adapter remains row-backed."},
		{ID: "homeassistant", DisplayName: "Home Assistant", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/homeassistant/adapter.py", GormesSurface: "internal/channels/homeassistant", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 7.E", Notes: "Hermes now exposes Home Assistant as a bundled platform plugin; state-change formatting and persistent notifications are native while richer plugin adapter parity remains partial."},
		{ID: "email", DisplayName: "Email", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/email/adapter.py", GormesSurface: "internal/channels/email", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 7.B", Notes: "Hermes moved Email to a bundled platform plugin; RFC822 normalization and reply-thread targets are native."},
		{ID: "sms", DisplayName: "SMS", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/sms/adapter.py", GormesSurface: "internal/channels/sms", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 7.B", Notes: "Hermes moved SMS to a bundled platform plugin; phone-number keys and outbound segmentation are native."},
		{ID: "dingtalk", DisplayName: "DingTalk", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/dingtalk/adapter.py", GormesSurface: "internal/channels/dingtalk", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E", Notes: "Hermes moved DingTalk to a bundled platform plugin; shared-bot ingress and Stream Mode bootstrap fixtures are native while live SDK binding is paused."},
		{ID: "api_server", DisplayName: "API server", Kind: PlatformKindRuntime, Status: PlatformStatusRowBacked, HermesSource: "gateway/platforms/api_server.py", GormesSurface: "internal/apiserver", Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 5.Q", Notes: "Runtime API surface; not an external chat channel."},
		{ID: "webhook", DisplayName: "Webhook", Kind: PlatformKindWebhook, Status: PlatformStatusImplemented, HermesSource: "gateway/platforms/webhook.py", GormesSurface: "internal/channels/webhook", Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 7.D / Phase 5.O", Notes: "Signed ingress and prompt-to-delivery bridge are native; management CLI is row-backed."},
		{ID: "msgraph_webhook", DisplayName: "Microsoft Graph webhook", Kind: PlatformKindWebhook, Status: PlatformStatusRowBacked, HermesSource: "gateway/platforms/msgraph_webhook.py", GormesSurface: "Phase 7.D row-backed webhook listener", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceNotApplicable, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceNotApplicable, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.D", Notes: "Fresh Hermes Graph change-notification listener; validationToken echo, clientState, source-CIDR, dedupe, and scheduler wiring remain row-backed."},
		{ID: "feishu", DisplayName: "Feishu", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/feishu/adapter.py", GormesSurface: "internal/channels/feishu", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes moved Feishu to a bundled platform plugin; shared-bot ingress and reply-target preservation are native; Drive/comment tool workflows remain row-backed."},
		{ID: "google_chat", DisplayName: "Google Chat", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/google_chat/adapter.py", GormesSurface: "internal/channels/googlechat", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes exposes Google Chat as a bundled platform plugin with Pub/Sub and standalone send hooks; Gormes has a fakeable runtime seam but live Google Chat API behavior remains row-backed."},
		{ID: "irc", DisplayName: "IRC", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/irc/adapter.py", GormesSurface: "Phase 7.E row-backed plugin channel", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes exposes IRC as a bundled stdlib platform plugin with env enablement and standalone cron delivery; no native Gormes IRC adapter exists yet."},
		{ID: "line", DisplayName: "LINE", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/line/adapter.py", GormesSurface: "Phase 7.E row-backed plugin channel", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes exposes LINE as a bundled platform plugin with HMAC webhook verification, reply-token/postback routing, LINE-sized chunks, media URL serving, env enablement, and standalone cron send; Gormes keeps it visible as row-backed until adapter fixtures exist."},
		{ID: "ntfy", DisplayName: "ntfy", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/ntfy/adapter.py", GormesSurface: "Phase 7.E row-backed plugin channel", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Fresh Hermes bundled platform plugin for ntfy notifications; no native Gormes adapter fixtures exist yet."},
		{ID: "simplex", DisplayName: "SimpleX Chat", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/simplex/adapter.py", GormesSurface: "internal/channels/simplex + cmd/gormes gateway", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Native fakeable SimpleX text ingress/outbound, env enablement, opaque contact IDs, allowlist evidence, home-channel delivery, and daemon status are present; QR/contact onboarding and media/file transfer remain explicit degraded follow-up work."},
		{ID: "teams", DisplayName: "Microsoft Teams", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/teams/adapter.py", GormesSurface: "internal/channels/teams + cmd/gormes gateway", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfacePartial, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes exposes Teams as a bundled platform plugin rather than a gateway Platform enum value; Gormes has the fakeable seam and config/status wiring, while live Bot Framework transport remains row-backed."},
		{ID: "wecom", DisplayName: "WeCom", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "plugins/platforms/wecom/adapter.py", GormesSurface: "internal/channels/wecom", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B.10", Notes: "Hermes moved WeCom to a bundled platform plugin; shared-bot and outbound lifecycle seams are native."},
		{ID: "wecom_callback", DisplayName: "WeCom callback", Kind: PlatformKindWebhook, Status: PlatformStatusImplemented, HermesSource: "gateway/platforms/wecom_callback.py", GormesSurface: "internal/channels/wecom", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B.10", Notes: "Callback mode is a platform-specific webhook surface, not a missing channel."},
		{ID: "weixin", DisplayName: "Weixin", Kind: PlatformKindChannel, Status: PlatformStatusImplemented, HermesSource: "gateway/platforms/weixin.py", GormesSurface: "internal/channels/weixin", RequiresLiveCredentials: true, Inbound: PlatformSurfaceImplemented, Outbound: PlatformSurfaceImplemented, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceImplemented, BacklogOwner: "Phase 2.B.10", Notes: "Shared-bot and reply-path contracts are native."},
		{ID: "bluebubbles", DisplayName: "BlueBubbles", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "gateway/platforms/bluebubbles.py", GormesSurface: "internal/channels/bluebubbles", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E", Notes: "Webhook auth, chat GUID cache, and home-channel fallback are native; iMessage bubble formatting is paused."},
		{ID: "qqbot", DisplayName: "QQ Bot", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "gateway/platforms/qqbot/", GormesSurface: "internal/channels/qqbot", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E", Notes: "Shared-bot policy and passive replies are native; token/gateway fake transport remains follow-up."},
		{ID: "yuanbao", DisplayName: "Yuanbao", Kind: PlatformKindChannel, Status: PlatformStatusPartial, HermesSource: "gateway/platforms/yuanbao.py", GormesSurface: "internal/channels/yuanbao", RequiresLiveCredentials: true, Inbound: PlatformSurfacePartial, Outbound: PlatformSurfacePartial, Media: PlatformSurfacePartial, Commands: PlatformSurfaceImplemented, Toolset: PlatformSurfacePartial, Config: PlatformSurfacePartial, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfacePartial, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Protobuf/markdown/media/sticker fixtures and disabled toolset registration are native; live catalog remains row-backed."},
		{ID: "whatsapp_cloud", DisplayName: "WhatsApp Business Cloud API", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "gateway/platforms/whatsapp_cloud.py", GormesSurface: "Phase 7.E row-backed WhatsApp Cloud API connector", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Fresh Hermes WhatsApp Business Cloud API connector via Meta Graph API; distinct from the bridge-based whatsapp platform; no native Gormes adapter fixtures exist yet."},
		{ID: "photon", DisplayName: "Photon iMessage", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/photon/adapter.py", GormesSurface: "Phase 7.E row-backed plugin channel", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceRowBacked, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes bundled plugin for iMessage via the Photon managed relay service; no native Gormes adapter fixtures exist yet."},
		{ID: "raft", DisplayName: "Raft", Kind: PlatformKindChannel, Status: PlatformStatusRowBacked, HermesSource: "plugins/platforms/raft/adapter.py", GormesSurface: "Phase 7.E row-backed plugin channel", RequiresLiveCredentials: true, Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceNotApplicable, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "Hermes bundled plugin connecting to Raft as an external agent via a local wake-channel bridge; the adapter owns a localhost wake endpoint and wake-hint injection while the agent drives Raft CLI reads/replies; no native Gormes adapter fixtures exist yet."},
		{ID: "relay", DisplayName: "Relay connector", Kind: PlatformKindRuntime, Status: PlatformStatusRowBacked, HermesSource: "gateway/relay/__init__.py", GormesSurface: "Phase 7.E row-backed relay connector surface", Inbound: PlatformSurfaceRowBacked, Outbound: PlatformSurfaceRowBacked, Media: PlatformSurfaceRowBacked, Commands: PlatformSurfaceRowBacked, Toolset: PlatformSurfaceRowBacked, Config: PlatformSurfaceRowBacked, Pairing: PlatformSurfaceNotApplicable, Delivery: PlatformSurfaceRowBacked, BacklogOwner: "Phase 7.E / Phase 5.A", Notes: "EXPERIMENTAL generic relay adapter fronted by an external connector; activated by GATEWAY_RELAY_URL; not a direct external channel — Gormes keeps it row-backed until the relay contract stabilises."},
	}
	return append([]PlatformManifestEntry(nil), manifest...)
}

// GormesOwnedPlatformManifest returns source-backed first-party channels that
// are intentionally outside Hermes' upstream Platform enum. These entries feed
// operator capability/status surfaces without weakening the Hermes parity
// manifest tests above.
func GormesOwnedPlatformManifest() []PlatformManifestEntry {
	manifest := []PlatformManifestEntry{
		{ID: "navivox", DisplayName: "Navivox", Kind: PlatformKindChannel, Status: PlatformStatusOwned, HermesSource: "gormes-owned:internal/adapters/channels/navivox", GormesSurface: "internal/adapters/channels/navivox + cmd/gormes gateway", RequiresLiveCredentials: true, Inbound: PlatformSurfaceOwned, Outbound: PlatformSurfaceOwned, Media: PlatformSurfacePartial, Commands: PlatformSurfacePartial, Toolset: PlatformSurfaceOwned, Config: PlatformSurfaceImplemented, Pairing: PlatformSurfacePartial, Delivery: PlatformSurfaceOwned, BacklogOwner: "Navivox first-party channel", Notes: "Gormes-owned HTTP/WebSocket channel for the Flutter Navivox app; not an upstream Hermes platform."},
	}
	return append([]PlatformManifestEntry(nil), manifest...)
}

// OperatorPlatformManifest combines upstream Hermes platform parity rows with
// Gormes-owned operator channels for capability/status reporting.
func OperatorPlatformManifest() []PlatformManifestEntry {
	manifest := HermesGatewayPlatformManifest()
	seen := map[string]struct{}{}
	for _, entry := range manifest {
		seen[entry.ID] = struct{}{}
	}
	for _, entry := range GormesOwnedPlatformManifest() {
		if _, ok := seen[entry.ID]; ok {
			continue
		}
		manifest = append(manifest, entry)
	}
	return append([]PlatformManifestEntry(nil), manifest...)
}
